---
title: "Trajectory Analysis"
output: html_notebook
---

Read in libraries

```{r}
library(Seurat)
library(SeuratWrappers)
library(monocle3)
library(tidyverse)

```

Read in data

```{r}

data <- readRDS("/data/CDSL_hannenhalli/Cole/projects/drug_treatment/data/processed_data/sciPlex_data/A549_processed_filtered.rds")
```

```{r}
data <- data[1:1000,1:1000]
```

```{r}
cds <- as.cell_data_set(data)
```

```{r}
cds
```

```{r}
fData(cds)$gene_short_name <- rownames(fData(cds))
```

```{r}
recreate.partition <- c(rep(1,length(cds@colData@rownames)))
names(recreate.partition) <- cds@colData@rownames
recreate.partition <- as.factor(recreate.partition)
```

```{r}
cds@clusters$UMAP$partition <- recreate.partition
```

```{r}
list_cluster <- data@active.ident
cds@clusters$UMAP$clusters <- list_cluster
```

```{r}
cds@int_colData@listData$reducedDims$UMAP <- data@reductions$UMAP@cell.embeddings
```

```{r}
cluster_before_traj <- plot_cells(cds,
           color_cells_by = 'cluster',
           label_groups_by_cluster = F,
           group_label_size = 5)+
  theme(legend.position='right')
```

```{r}
cluster_before_traj
```

```{r}
cds <- learn_graph(cds,use_partition = T)

```

```{r}
cat("ff")
```

```{r}
names(cds@clusters$UMAP$partition)
```

```{r}
cluster_after_traj <- plot_cells(cds,
           color_cells_by = 'cluster',
           label_groups_by_cluster = F,
           label_branch_pints = F,
           label_roots = F,
           label_leaves = F,
           group_label_size = 5)+
  theme(legend.position='right')
```
